var carName = "Volvo";
console.log(carName);
var x = 50;
console.log(x);
var num1 = 5;
var num2 = 10;
document.getElementById("demo").innerHTML = x+y;
var z = x+y;
alert(z);
var firstName ="John", lastName ="Doe", age =35;